<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb8fd9f17e10faaf8eeb0572f1e6cb5d8
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DLXPlugins\\PowerBlocks\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DLXPlugins\\PowerBlocks\\' => 
        array (
            0 => __DIR__ . '/../..' . '/php',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb8fd9f17e10faaf8eeb0572f1e6cb5d8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb8fd9f17e10faaf8eeb0572f1e6cb5d8::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb8fd9f17e10faaf8eeb0572f1e6cb5d8::$classMap;

        }, null, ClassLoader::class);
    }
}
